// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Voitures.Data;

namespace Voitures.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20211124154645_Client")]
    partial class Client
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Voitures.Data.Models.Voiture", b =>
                {
                    b.Property<int>("IdVoiture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Couleur")
                        .HasColumnType("text");

                    b.Property<string>("Marque")
                        .HasColumnType("text");

                    b.Property<string>("Modele")
                        .HasColumnType("text");

                    b.HasKey("IdVoiture");

                    b.ToTable("Voitures");
                });
#pragma warning restore 612, 618
        }
    }
}
